[global]
error_log = /dev/stderr

[www]
user = app
group = app
listen = 127.0.0.1:9000
clear_env = no
catch_workers_output = yes
decorate_workers_output = no

pm = ondemand
pm.max_children = 25
pm.process_idle_timeout = 15s
pm.max_requests = 500

pm.status_path = /fpm-status
ping.path = /fpm-ping
ping.response = pong

request_terminate_timeout = 120s
rlimit_files = 4096
